server:
  port: 9001

#spring:
#  application:
#    name: tensquare-base
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.71.139:3306/tensquare_base?characterEncoding=utf-8
#    username: root
#    password: root
#  jpa:
#    database: mysql
#    show-sql: true

spring:
  application:
    name: tensquare-base #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.101.211.49:3306/tensquare_base?characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true   #解决跨域