server:
  port: 9008
#spring:
#  application:
#    name: tensquare-user #指定服务名
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
##        虚拟机docker
#    url: jdbc:mysql://192.168.71.139:3306/tensquare_user?characterEncoding=UTF8
#    username: root
#    password: root
#  jpa:
#    database: MySQL
#    show-sql: true
#  redis:
#    host: 192.168.71.139
#  rabbitmq:
#    host: 192.168.71.139
#jwt:
#  config:
#    key: noShampoo     #盐
#    ttl: 3600000       #过期时间(单位毫秒)



  #    阿里云服务器http://39.101.211.49/
spring:
  application:
    name: tensquare-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.101.211.49:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: 39.101.211.49
  rabbitmq:
    host: 39.101.211.49
jwt:
  config:
    key: noShampoo
    ttl: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
